# -*- coding: utf-8 -*-
"""Coordinates of a number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100HUV0aztj9YKTcyLH1nKCU5V1Eahs6V

# **Coordinates.**

Locate a point on the Cartesian coordinate plane: which of the four quadrants does a point belong to?


Read two numbers from the input, not necessarily integers, the first number will indicate a position on the X-axis, the second one — on the Y-axis. Let's keep referring to the quadrants by Roman numerals, as shown in the picture.

If the point is the **origin** (0, 0), **print "It's the origin!"**. If a point lies on the axes, with **either x = 0 or y = 0**, **print "One of the coordinates is equal to zero!**"
"""

x = float(input("Enter your x coordinates"))
y = float(input("Enter your y coordinates"))
if x==0 and y==0:
    print("It's the origin!")
elif x > 0 and y>0:
    print("Your coordinates belongs to I Cartesian coordinate plane.")
elif x>0 and y<0:
    print("Your coordinates belongs to II Cartesian coordinate plane.")
elif x<0 and y>0:
    print("Your coordinates belongs to III Cartesian coordinate plane.")
elif x<0 and y<0:
    print("Your coordinates belongs to IV Cartesian coordinate plane.")
else:
    print("One of the coordinates is equal to zero!")